int pinLED = 13;

void setup() {
  pinMode(pinLED, OUTPUT);
  Serial.begin(9600);
  Serial.println("Bomb has been planted !");
  delay(100);
  Serial.println("times set to 44 seconds");
}

void loop() {
  digitalWrite(pinLED, HIGH);
  Serial.println("44 seconds remaining");
  delay(300);
  digitalWrite(pinLED, LOW);
  Serial.println("43 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("42 seconds remaining");
  delay(100);
  digitalWrite(pinLED, LOW);
  Serial.println("41 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("40 seconds remaining");
  delay(500);
  digitalWrite(pinLED, LOW);
  Serial.println("39 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("38 seconds remaining");
  delay(100);
  digitalWrite(pinLED, LOW);
  Serial.println("37 seconds remaining");
  delay(200);
  digitalWrite(pinLED, HIGH);
  Serial.println("36 seconds remaining");
  delay(300);
  digitalWrite(pinLED, LOW);
  Serial.println("35 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("34 seconds remaining");
  delay(100);
  digitalWrite(pinLED, LOW);
  Serial.println("33 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("32 seconds remaining");
  delay(500);
  digitalWrite(pinLED, LOW);
  Serial.println("31 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("30 seconds remaining");
  delay(100);
  digitalWrite(pinLED, LOW);
  Serial.println("29 seconds remaining");
  delay(200);
  digitalWrite(pinLED, HIGH);
  Serial.println("28 seconds remaining");
  delay(300);
  digitalWrite(pinLED, LOW);
  Serial.println("27 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("26 seconds remaining");
  delay(100);
  digitalWrite(pinLED, LOW);
  Serial.println("25 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("24 seconds remaining");
  delay(500);
  digitalWrite(pinLED, LOW);
  Serial.println("23 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("22 seconds remaining");
  delay(100);
  digitalWrite(pinLED, LOW);
  Serial.println("21 seconds remaining");
  delay(200);
  digitalWrite(pinLED, HIGH);
  Serial.println("20 seconds remaining");
  delay(300);
  digitalWrite(pinLED, LOW);
  Serial.println("19 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("18 seconds remaining");
  delay(2000);
  digitalWrite(pinLED, LOW);
  Serial.println("17 seconds remaining");
  delay(100);
  Serial.println("Time skipped, failed defuse!");
  delay(1000);
  digitalWrite(pinLED, HIGH);
  Serial.println("10 seconds remaining");
  delay(2000);
  digitalWrite(pinLED, LOW);
  Serial.println("8 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("7 seconds remaining");
  delay(2000);
  digitalWrite(pinLED, LOW);
  Serial.println("6 seconds remaining");
  delay(50);
  digitalWrite(pinLED, HIGH);
  Serial.println("5 seconds remaining");
  delay(100);
  digitalWrite(pinLED, LOW);
  Serial.println("4 seconds remaining");
  delay(50);
  digitalWrite(pinLED, HIGH);
  Serial.println("3 seconds remaining");
  delay(100);
  digitalWrite(pinLED, LOW);
  Serial.println("2 seconds remaining");
  delay(50);
  digitalWrite(pinLED, HIGH);
  Serial.println("1 seconds remaining");
  delay(100);
  digitalWrite(pinLED, HIGH);
  Serial.println("Bomb has been explode!");
  delay(3000);
  Serial.println("Terorist Win!");
  delay(5000);
  digitalWrite(pinLED, LOW);
  delay(10000);
}
